warnings_are_errors: false

language: java

jdk: openjdk8

script: mvn install -B

after_success:
  - cd aurkitu-maven-plugin && mvn jacoco:report org.eluder.coveralls:coveralls-maven-plugin:report
  - cd ../aurkitu-annotations && mvn jacoco:report org.eluder.coveralls:coveralls-maven-plugin:report
  - cd ../ && pip install --user codecov && codecov
