warnings_are_errors: false

language: java

jdk: openjdk8

script: mvn install -B

after_success:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report
  - pip install --user codecov && codecov
