# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline --projects aurkitu-annotations,aurkitu-maven-plugin
      - run: mvn dependency:get -Dartifact=org.apache.maven.plugins:maven-install-plugin:2.4
      - run: mvn dependency:get -Dartifact=org.jacoco:jacoco-maven-plugin:0.8.4
      - run: mvn dependency:get -Dartifact=junit:junit:4.8.2
      - run: mvn dependency:get -Dartifact=org.apache.maven:maven-repository-metadata:2.0.10
      - run: mvn dependency:get -Dartifact=commons-collections:commons-collections:3.2.2
      - run: mvn dependency:get -Dartifact=org.apache.maven:maven-core:2.0.6
      - run: mvn dependency:get -Dartifact=org.apache.maven:maven-monitor:2.0.6
      - run: mvn dependency:get -Dartifact=org.apache.maven.shared:maven-filtering:1.1
      - run: mvn dependency:get -Dartifact=org.codehaus.plexus:plexus-interpolation:1.13
      - run: mvn dependency:get -Dartifact=org.codehaus.plexus:plexus-component-annotations:1.6
      - run: mvn dependency:get -Dartifact=org.apache.maven.shared:maven-shared-utils:3.1.0
      - run: mvn dependency:get -Dartifact=org.apache.maven.shared:maven-shared-incremental:1.1
      - run: mvn dependency:get -Dartifact=org.codehaus.plexus:plexus-java:0.9.2
      - run: mvn dependency:get -Dartifact=org.codehaus.plexus:plexus-compiler-api:2.8.2
      - run: mvn dependency:get -Dartifact=org.codehaus.plexus:plexus-compiler-manager:2.8.2
      - run: mvn dependency:get -Dartifact=org.codehaus.plexus:plexus-compiler-javac:2.8.2

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn clean -o install -T 1C
      - run: cd aurkitu-test-service/ && mvn clean install -f pom-test.xml