name: Maven Plugin CI

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@master
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8 
          
      - name: Build with script
        run: ./build-test.sh
        
#      - name: Publish to coveralls.io
#        uses: coverallsapp/github-action@v2
#        with:
#            base-path: aurkitu-maven-plugin/src/main/java
#            file: aurkitu-maven-plugin/target/jacoco-ut/jacoco.xml
#           parallel: true  
#          
#      - name: Publish coverage report
#        run: |
#          cd aurkitu-maven-plugin && mvn jacoco:report org.eluder.coveralls:coveralls-maven-plugin:report
#          cd ../aurkitu-annotations && mvn jacoco:report org.eluder.coveralls:coveralls-maven-plugin:report
#          cd ../ && pip install --user codecov && codecov
